### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by graham-m-dunn** [ailionx/cloudflare-ddns#12]
Would you consider a new release incorporating the fix-malformed-json-error fix?

Thanks,
Graham

**Comment by ailionx** [comment]
@graham-m-dunn I will release a new version shortly.

**Comment by ailionx** [comment]
A new version is released. https://pypi.org/project/cloudflare-ddns/1.3.0/. It was a bit in a rush. Please let me know if there is any issue with that. Cheers.
