### ISSUE TITLE
Is it possible to add a wildcard domain?

### ISSUE THREAD

**Issue by wshayes** [ailionx/cloudflare-ddns#5]
Thanks - this is a great library/CLI.  Was just what I was looking for to slide out from under the tyranny of AWS ElasticIP's :)

Just wondering if it's possible to use this to update wildcard entries as well.  I register the host domain, but I also want any subdomains to be pointed to the same IP.

**Comment by isaacnoboa** [comment]
Simply using "*.example.com" as the domain allowed me to update the wildcard entry. In my case, I had a command that looks like this:

```python
for i in config.domains:
    print(i+": ", end="")
    cf=CloudFlare(config.email, config.api_key, i)
    cf.refresh()
    cf.sync_dns_from_my_ip()
```
(with "*.example.com" being in the list named config.domains)

And then the output looked like this:

```
*.example.com: DNS record successfully updated
Successfully updated IP address from 127.0.0.1 to 0.0.0.0
```
