### ISSUE TITLE
Examples gives error

### ISSUE THREAD

**Issue by jasperdanan** [ailionx/cloudflare-ddns#9]
## Error
In the [examples](https://github.com/ailionx/cloudflare-ddns#examples) for the repo

The "Python Code" example:
```py
from cloudflare_ddns import CloudFlare
cf = CloudFlare(email, api_key, domain)
cf.sync_dns_from_my_ip() # Successfully updated IP address from xx.xx.xx.xx to xx.xx.xx.xx
```

Gives this error:
```py
TypeError: __init__() missing 1 required positional argument: 'proxied'
```

## Solution(?)
Added the parameter for `proxied` in `CloudFlare()` as boolean

Like so:
```py
from cloudflare_ddns import CloudFlare
cf = CloudFlare(email, api_key, domain, proxied)
cf.sync_dns_from_my_ip() # Successfully updated IP address from xx.xx.xx.xx to xx.xx.xx.xx
```

**Comment by ailionx** [comment]
This is fixed by giving the default value for `proxied` as `False`. In d61b278fbc0ffd54d8a364e9f8b28bd813cce537
